name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: test
        run: |
          npm ci
          npm test
